### ISSUE TITLE
Nice MNIST `hello world`, one minor detail

### ISSUE THREAD

**Issue by wbaik** [virgax7/ml-Adventures#1]
I haven't cloned it, so I could be mistaken.

On [`In [116]`](https://github.com/virgax7/ml-Adventures/blob/master/python-stuff/mnist/MNIST.ipynb), 
`weights[k][j] -= delta[j]*inputs[k]`, shouldn't we have something like `eps` or a constant `learning rate` to decrease the learning rate? It looks kinda awkward without it. I think this applies to some other cells, as similar idea arises. 

Again I could be mistaken... haha

**Comment by virgax7** [comment]
Hmm, perhaps its something I'm unaware of since I'm so new to this

Could you demonstrate with an example please? From what I'm gathering, do you mean an alpha like 
on **In [126]**
```
    inputs = np.array(data[0][1:])
    # tone down the input
    alpha = .0001
    inputs = inputs * alpha

```

**Comment by wbaik** [comment]
Yea, that takes care of it.
